/**
 * NELFUND AI answer playbook
 */
import type { IntentId } from './types'
import { eligibilityAnswer } from './eligibilityAnswer'
import { playbookPendingExtras } from './playbookPendingExtras'
import { playbookHourly112 } from './playbookHourly112'
import { playbookHourly113 } from './playbookHourly113'
import { playbookHourly106 } from './playbookHourly106'
import { playbookHourly116 } from './playbookHourly116'
import { playbookHourly117 } from './playbookHourly117'
import { playbookHourly118 } from './playbookHourly118'
import { playbookHourly119 } from './playbookHourly119'
import { playbookHourly120 } from './playbookHourly120'
import { playbookHourly121 } from './playbookHourly121'
import { playbookHourly122 } from './playbookHourly122'
import { playbookHourly123 } from './playbookHourly123'
import { playbookHourly124 } from './playbookHourly124'
import { playbookHourly125 } from './playbookHourly125'
import { playbookHourly126 } from './playbookHourly126'
import { playbookHourly127 } from './playbookHourly127'
import { playbookHourly136 } from './playbookHourly136'
import { playbookHourly139 } from './playbookHourly139'
import { playbookHourly140 } from './playbookHourly140'

const PORTAL = 'https://portal.nelf.gov.ng/'
const SITE = 'https://nelf.gov.ng/'
const ESUPPORT = 'https://nelfund.esupport.ng/create'
const FAQ = 'https://nelf.gov.ng/faq'
