/**
 * NELFUND AI answer playbook
 */
import type { IntentId } from './types'
import { eligibilityAnswer } from './eligibilityAnswer'
import { playbookPendingExtras } from './playbookPendingExtras'
import { playbookHourly53 } from './playbookHourly53'
import { playbookHourly54 } from './playbookHourly54'
import { playbookHourly55 } from './playbookHourly55'
import { playbookHourly56 } from './playbookHourly56'
import { playbookHourly57 } from './playbookHourly57'
import { playbookHourly58 } from './playbookHourly58'
import { playbookHourly59 } from './playbookHourly59'
import { playbookHourly60 } from './playbookHourly60'
import { playbookHourly61 } from './playbookHourly61'
import { playbookHourly62 } from './playbookHourly62'
import { playbookHourly63 } from './playbookHourly63'
import { playbookHourly64 } from './playbookHourly64'
import { playbookHourly65 } from './playbookHourly65'
import { playbookHourly66 } from './playbookHourly66'

const PORTAL = 'https://portal.nelf.gov.ng/'
const SITE = 'https://nelf.gov.ng/'
const ESUPPORT = 'https://nelfund.esupport.ng/create'
const FAQ = 'https://nelf.gov.ng/faq'
