/**
 * NELFUND AI answer playbook
 */
import type { IntentId } from './types'
import { eligibilityAnswer } from './eligibilityAnswer'
import { playbookPendingExtras } from './playbookPendingExtras'
import { playbookHourly53 } from './playbookHourly53'
import { playbookHourly54 } from './playbookHourly54'
import { playbookHourly55 } from './playbookHourly55'
import { playbookHourly56 } from './playbookHourly56'
import { playbookHourly57 } from './playbookHourly57'
import { playbookHourly58 } from './playbookHourly58'
import { playbookHourly59 } from './playbookHourly59'
import { playbookHourly60 } from './playbookHourly60'
import { playbookHourly61 } from './playbookHourly61'
import { playbookHourly62 } from './playbookHourly62'
import { playbookHourly63 } from './playbookHourly63'
import { playbookHourly64 } from './playbookHourly64'
import { playbookHourly65 } from './playbookHourly65'
import { playbookHourly66 } from './playbookHourly66'
import { playbookHourly67 } from './playbookHourly67'
import { playbookHourly68 } from './playbookHourly68'
import { playbookHourly69 } from './playbookHourly69'
import { playbookHourly70 } from './playbookHourly70'
import { playbookHourly71 } from './playbookHourly71'
import { playbookHourly72 } from './playbookHourly72'
import { playbookHourly73 } from './playbookHourly73'
import { playbookHourly74 } from './playbookHourly74'
import { playbookHourly75 } from './playbookHourly75'
import { playbookHourly82 } from './playbookHourly82'
import { playbookHourly87 } from './playbookHourly87'
import { playbookHourly88 } from './playbookHourly88'
import { playbookHourly89 } from './playbookHourly89'
import { playbookHourly90 } from './playbookHourly90'
import { playbookHourly91 } from './playbookHourly91'
import { playbookHourly92 } from './playbookHourly92'
import { playbookHourly93 } from './playbookHourly93'
import { playbookHourly94 } from './playbookHourly94'
import { playbookHourly95 } from './playbookHourly95'
import { playbookHourly96 } from './playbookHourly96'
import { playbookHourly97 } from './playbookHourly97'
import { playbookHourly98 } from './playbookHourly98'
import { playbookHourly104 } from './playbookHourly104'
import { playbookHourly112 } from './playbookHourly112'
import { playbookHourly106 } from './playbookHourly106'
